### ISSUE TITLE
Fail to set player.currentTime when using as a component in typescript react app

### ISSUE THREAD

**Issue by matthewgan** [art-mironoff/react-video-markers#2]
I tried to modify your code into jsx, and using this as a component in other react apps, 

but when click on progress or click on marker, the player.currentTime will always jump to 0 

instead of jump to when it clicked.

Any hint appriated.

**Comment by art-mironoff** [comment]
Hello, I added **isPlaying**, **controls**, **height**, **width**, **volume**, **loop** props and **onPlay**, **onPause**, **onVolume**, **onProgress**, **onDuration** callbacks. So you can use **isPlaying** prop for starting and pausing player. Also now you need to use **volume**, **onPlay**, **onPause** and **onVolume** callbacks.

P.S. This component hasn`t finished and maybe it has bugs, sorry for that :)

**Comment by matthewgan** [comment]
Thanks a lot for the reply.
I found the progress bar and marker not working if the frame rate of video is 23.976.
So it should be some problem with the source video or something deeper, your code is clear enough.
Appreciated~
